# Generated by Django 5.0.6 on 2024-06-26 16:11

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_book_publish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='poster',
            field=models.ImageField(default='books/images/default.png', null=True, upload_to=home.models.imagesave),
        ),
    ]
